### ISSUE TITLE
When clicking a button it does not teleport the player.

### ISSUE THREAD

**Issue by iiFlamiinBlaze** [PlexusStudio/WorldTpUI#2]
When you tap on any button for a world after doing /wtpui, it does not teleport you.

**Comment by AvgZing** [comment]
I do not believe that we have fully set up the actual teleportation feature yet, only the UI... I'll double check and get back to you on this.

**Comment by ZeroDevOfficial** [comment]
@iiFlamiinBlaze hmm when I tested it, it was working, let me see if it works for me still

**Comment by ZeroDevOfficial** [comment]
@iiFlamiinBlaze I just created a new server with no other plugins, I loaded my plugin, stopped my server and started it back up, I was able to teleport between all the worlds I had loaded

if haven't I would recommend turning the ```load_all_worlds``` on in the 'config.yml'

also make sure your pocketmine is up to date, we do not recommend using any fork or spoon if your not using pmmp

and make sure your using the latest version of the plugin [here](https://github.com/PlexusStudio/WorldTpUI/releases)

```YML
#config
---
version: 0.0.2
load_all_worlds: true
...
```

```
console log:

[14:19:44] [Server thread/INFO]: [WorldTpUI] is Loading...
[14:19:44] [Server thread/INFO]: [WorldTpUI] Plugin Config is update-to-date.
[14:19:44] [Server thread/INFO]: Preparing level "world"
[14:19:44] [Server thread/INFO]: [WorldTpUI] Level: test Has Been Added to UI List as 0
[14:19:44] [Server thread/INFO]: [WorldTpUI] Level: world Has Been Added to UI List as 1
[14:19:44] [Server thread/INFO]: [WorldTpUI] Everything has Loaded!
```

in-game:
![2017-11-10 4](https://user-images.githubusercontent.com/12077835/32682789-d470c6b4-c62b-11e7-888b-24e701fd3750.png)

**Comment by ghost** [comment]
I tried clicking the buttons and nothing happened for me too, plugin loaded fine

**Comment by ZeroDevOfficial** [comment]
@David-AI can you please provide me a list of all your plugins loaded and are you using the latest version of pmmp?

or are you using a fork/spoon of pmmp

**Comment by ZeroDevOfficial** [comment]
@iiFlamiinBlaze @David-AI try using the latest update

https://github.com/PlexusStudio/WorldTpUI/releases

**Comment by ghost** [comment]
Everything seems fixed, Thanks!

**Comment by ZeroDevOfficial** [comment]
@iiFlamiinBlaze can u see if the issue has been fixed

https://github.com/PlexusStudio/WorldTpUI/releases

**Comment by ZeroDevOfficial** [comment]
@iiFlamiinBlaze this issue is probably fixed, if you still have the issue let me know and I'll reopen this issue but unless I get a response it will stay closed
